import { StyleSheet } from 'react-native';

const estilos = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    width: '100%',
    minHeight: '100vh',
  },
  conteudo: {
    backgroundColor: '#FFFACD',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    width: '100%',
    minHeight: '100vh',
  },
  conteudoInterno: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  inputNome: {
    borderWidth: 1,
    borderColor: '#FFD700',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginVertical: 10,
    fontSize: 14,
    backgroundColor: '#FFFFFF',
  },
  inputObservacoes: {
    borderWidth: 1,
    borderColor: '#FFD700',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginVertical: 10,
    fontSize: 14,
    backgroundColor: '#FFFFFF',
    minHeight: 60,
    textAlignVertical: 'top',
  },
  picker: {
    height: 50,
    width: '100%',
    borderColor: '#FFD700',
    borderWidth: 2,
    borderRadius: 8,
    marginVertical: 10,
  },
  botao: {
    backgroundColor: '#4CAF50',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  textoBotao: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  imagem: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginVertical: 15,
  },
  textoConteudo: {
    fontSize: 14,
    color: '#666',
    marginTop: 15,
    fontWeight: '600',
  },
  tituloConteudo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 15,
  },
  textoResultado: {
    fontSize: 14,
    color: '#333',
    fontWeight: 'bold',
    marginTop: 15,
    textAlign: 'center',
    paddingHorizontal: 10,
    minHeight: 60,
    backgroundColor: '#FFF8DC',
    borderRadius: 8,
    paddingVertical: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#4CAF50',
  },
});

export default estilos;
